Protectores/Controllers/AdopcionAnimalController.cs
using Protectores.DAL;
using Protectores.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Protectores.Controllers
{
    public class AdopcionAnimalController : Controller
    {
        private ProtectoresContext db = new ProtectoresContext();

        // GET: AdopcionAnimal
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdopcionAnimal/List
        public ActionResult List()
        {
            return View(db.AdopcionAnimal);
        }

        // GET: AdopcionAnimal/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdopcionAnimal/Create
        [HttpPost]
        public ActionResult Create(AdopcionAnimal adopcion)
        {
            try
            {
                int formID = int.Parse(Session["UsuarioId"].ToString());
                adopcion.Usuario = db.Usuarios.Find(formID);
                db.AdopcionAnimal.Add(adopcion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Protectores/Controllers/RegistracionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Protectores.DAL;
using Protectores.Models;
using GoogleEntities;
using GoogleApiRequest;

namespace Protectores.Controllers
{
    public class RegistracionController : Controller
    {
        private ProtectoresContext db = new ProtectoresContext();

        // GET: Registracion/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Registracion/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contacto contacto)
        {
            GeocodeResponse geoPosicion = GoogleConnector.MakeRequest(contacto.AddressNumber, contacto.StreetName, contacto.CityName, contacto.CountryName.ToString());
            Console.WriteLine(geoPosicion);
            contacto.Latitud = geoPosicion.results[0].geometry.location.lat;
            contacto.Longitud = geoPosicion.results[0].geometry.location.lng;

            db.Contacto.Add(contacto);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        // GET: Registracion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
           }
            Contacto contacto = db.Contacto.Find(id);
            if (contacto == null)
            {
                return HttpNotFound();
            }
            return View(contacto);
        }

        // POST: Registracion/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                GeocodeResponse geoPosicion = GoogleConnector.MakeRequest(contacto.AddressNumber, contacto.StreetName, contacto.CityName, contacto.CountryName.ToString());
                Console.WriteLine(geoPosicion);
                contacto.Latitud = geoPosicion.results[0].geometry.location.lat;
                contacto.Longitud = geoPosicion.results[0].geometry.location.lng;
                contacto.Usuario.UsuarioId = int.Parse(Session["UsuarioId"].ToString());
                contacto.UsuarioId = contacto.Usuario.UsuarioId;
                db.Entry(contacto.Usuario).State = EntityState.Modified;
                db.Entry(contacto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

Protectores/Views/Shared/_Layout.cshtml
@{
    Boolean logged = (Boolean)Session["Logged"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Protectores", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (logged)
                    {
                        <li>@Html.ActionLink("Adopciones", "Index", "AdopcionAnimal")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!logged)
                    {
                        <li>@Html.ActionLink("Registrarse", "Create", "Registracion")</li>
                    }
                    @if (!logged)
                    {
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    }
                    @if (logged)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Protectores</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>